### ISSUE TITLE
Keys not visible across browsers

### ISSUE THREAD

**Issue by onktak** [asbiin/laravel-webauthn-example#751]
Hello,

I have deployed the demo app locally and realized that the when I register a key with like Firefox and then open Chrome to login via webauthn, the option to login using keys is not visible. It always presents the email and password authentication option.  Is this by design that the keys are only visible on the browser that you registered on.

**Comment by asbiin** [comment]
This is by design. When a user never logged in yet, they must first login with password.
This could be changed: if you enter your email, then you might be able to get proper data to login with keys. However in this case anyone will be able to check if the user has an account with the email. I don't know if it's secure enough. Any though?

**Comment by asbiin** [comment]
@onktak I made some changes in the login page, so now you can enter a username at login with a security key, which should solve your issue. Thank your for reporting!
